
development:
  adapter: postgresql
  database: camaras_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: root


test:
  adapter: postgresql
  database: camaras_test
  pool: 5
  timeout: 5000
  username: postgres
  password: root

