# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Camara.destroy_all
Camara.create(direccion: "Av. 80 - Calle 30", sector: "Avenida 80 - Calle 30 - Metroplus", link: "http://www.medellin.gov.co/transito/images_jq/imagen22.jpg")
Camara.create(direccion: "Carrera 62 - Calle 37 Puente de La 33", sector: "Avenida Regional - Puente de la 33", link: "http://www.medellin.gov.co/transito/images_jq/imagen2.jpg")
Camara.create(direccion: "Calle 16 - Carrera 32", sector: "Avenida Las Palmas - Resto- Asia", link: "http://www.medellin.gov.co/transito/images_jq/imagen3.jpg")
Camara.create(direccion: "Carrera 64C - Calle 67 Coca Cola", sector: "Autopista Norte - Fiscalia -Coca cola", link: "http://www.medellin.gov.co/transito/images_jq/imagen4.jpg")
Camara.create(direccion: "Carrera 64C - Calle 104 Zenu", sector: "Autopista Norte - Zenu", link: "http://www.medellin.gov.co/transito/images_jq/imagen5.jpg")
Camara.create(direccion: "Autopista Norte - Solla", sector: "Carrera 64A - Calle 114 A Solla	", link: "http://www.medellin.gov.co/transito/images_jq/imagen6.jpg")
Camara.create(direccion: "Carrera 63 - Calle 77 Puente del Mico", sector: "Puente del Mico - Estacion Caribe", link: "http://www.medellin.gov.co/transito/images_jq/imagen7.jpg")
Camara.create(direccion: "Carrera 64C - Calle 78 Terminal del Norte", sector: "Autopista Norte - Terminal de Transporte", link: "http://www.medellin.gov.co/transito/images_jq/imagen8.jpg")
Camara.create(direccion: "Carrera 62 - Calle 58", sector: "Horacio Toro", link: "http://www.medellin.gov.co/transito/images_jq/imagen9.jpg")
Camara.create(direccion: "Carrera 63 - Calle 48 Suramericana", sector: "Autopista Sur - Suramericana - Edificio Camacol", link: "http://www.medellin.gov.co/transito/images_jq/imagen10.jpg")
Camara.create(direccion: "Carrera 62 - Calle 44 Puente San Juan", sector: "Avenida Regional - San Juan", link: "http://www.medellin.gov.co/transito/images_jq/imagen11.jpg")
Camara.create(direccion: "Carrera 49 - Calle 30 Bancolombia", sector: "Avenida Regional - Puente de la 30 - Bancolombia", link: "http://www.medellin.gov.co/transito/images_jq/imagen12.jpg")
Camara.create(direccion: "Carrera 50 - Calle 4 Coltabaco", sector: "Autopista Sur - Coltabacos", link: "http://www.medellin.gov.co/transito/images_jq/imagen13.jpg")
Camara.create(direccion: "Carrera 49 - Calle 10 Sur La Aguacatala", sector: "Avenida Regional - La Aguacatala - EAFIT", link: "http://www.medellin.gov.co/transito/images_jq/imagen14.jpg")
Camara.create(direccion: "Carrera 46 - Calle 52 Oriental Playa", sector: "Avenida Oriental - La Playa", link: "http://www.medellin.gov.co/transito/images_jq/imagen15.jpg")
Camara.create(direccion: "Carrera 50 - Calle 31", sector: "Autopista Sur - Puente de Guayaquil", link: "http://www.medellin.gov.co/transito/images_jq/imagen16.jpg")
Camara.create(direccion: "Carrera 63  -  Calle 104 A", sector: "Avenida Regional - detras de la Feria de Ganado - Quebrada Tinajas", link: "http://www.medellin.gov.co/transito/images_jq/imagen17.jpg")
Camara.create(direccion: "Carrera 63 - Calle 94 A", sector: "Avenida Regional - Tricentenario- Quebrada Minitas", link: "http://www.medellin.gov.co/transito/images_jq/imagen18.jpg")
Camara.create(direccion: "Carrera 63A - Calle 38", sector: "Autopista Sur - Conquistadores", link: "http://www.medellin.gov.co/transito/images_jq/imagen19.jpg")
Camara.create(direccion: "Carrera 63A - Calle 15", sector: "Avenida Regional - Calle 16 - Home Center - high Light", link: "http://www.medellin.gov.co/transito/images_jq/imagen20.jpg")
Camara.create(direccion: "Carrera 49 - Calle 7", sector: "Avenida Regional - Calle 7 - INEM", link: "http://www.medellin.gov.co/transito/images_jq/imagen21.jpg")
Camara.create(direccion: "Av. 80 - Calle 30", sector: "Avenida 80 - Calle 30 - Metroplus", link: "http://www.medellin.gov.co/transito/images_jq/imagen22.jpg")
Camara.create(direccion: "Carrera 50FF - Calle 8 Sur", sector: "Avenida 80 - 50FF - Vivero - Familia", link: "http://www.medellin.gov.co/transito/images_jq/imagen23.jpg")
Camara.create(direccion: "Carrera 50FF - Calle 12 Sur", sector: "Avenida 80 - La FLA", link: "http://www.medellin.gov.co/transito/images_jq/imagen24.jpg")
Camara.create(direccion: "Carrera 52 - Calle 8 Surr", sector: "Avenida Guayabal - 8 Sur", link: "http://www.medellin.gov.co/transito/images_jq/imagen25.jpg")
Camara.create(direccion: "Carrera 52 - Calle 14", sector: "Avenida Guayabal - CEOH- Caribe Motor", link: "http://www.medellin.gov.co/transito/images_jq/imagen26.jpg")
Camara.create(direccion: "Carrera 43A - Calle 12 Sur", sector: "Avenida El Poblado - Virgen de La Aguacatala", link: "http://www.medellin.gov.co/transito/images_jq/imagen27.jpg")
Camara.create(direccion: "Carrera 43A - Calle 26 (Astor)", sector: "Avenida Poblado - Calle 30 - Astor - Dislicores", link: "http://www.medellin.gov.co/transito/images_jq/imagen28.jpg")
Camara.create(direccion: "Carrera 32 - Calle 9 Sur", sector: "Transversal Inferior - Los Balsos", link: "http://www.medellin.gov.co/transito/images_jq/imagen29.jpg")
Camara.create(direccion: "Carrera 30 - Calle 6", sector: "Transversal Inferior - Loma del Tesoro", link: "http://www.medellin.gov.co/transito/images_jq/imagen30.jpg")
Camara.create(direccion: "Carrera 25 - Calle 12 Sur", sector: "Transversal Superior - Los Balsos", link: "http://www.medellin.gov.co/transito/images_jq/imagen31.jpg")
Camara.create(direccion: "Carrera 38 - Calle 26", sector: "Avenida Las Palmas - Unidad Residencia Punta Piedra", link: "http://www.medellin.gov.co/transito/images_jq/imagen32.jpg")
Camara.create(direccion: "Carrera 48 - Calle 19", sector: "Avenida Industriales - Ciudad del Rio", link: "http://www.medellin.gov.co/transito/images_jq/imagen33.jpg")
Camara.create(direccion: "Carrera 70 - Calle 54", sector: "La Iguana", link: "http://www.medellin.gov.co/transito/images_jq/imagen34.jpg")
Camara.create(direccion: "Carrera 64  -  Calle 97", sector: "Autopista Norte - Parque Juanes de la Paz", link: "http://www.medellin.gov.co/transito/images_jq/imagen35.jpg")
Camara.create(direccion: "Carrera 30 - Calle 10", sector: "Transversal Inferior - Calle 10 - Carulla", link: "http://www.medellin.gov.co/transito/images_jq/imagen36.jpg")
Camara.create(direccion: "Carrera 50 - Calle 14", sector: "Autopista Sur - Calle 14 - Leonisa", link: "http://www.medellin.gov.co/transito/images_jq/imagen37.jpg")
Camara.create(direccion: "Carrera 66 B - Calle 42C", sector: "Avenida Bolivariana - San Juan - Deprimido Los Musicos", link: "http://www.medellin.gov.co/transito/images_jq/imagen38.jpg")
Camara.create(direccion: "Calle 10A con la 34", sector: "Hotel 10", link: "http://www.medellin.gov.co/transito/images_jq/imagen39.jpg")
Camara.create(direccion: "Carrera 65 - Transversal 78", sector: "Carrera 65 - Transversal 78 - Castipan - Glorieta Terminal del Norte", link: "http://www.medellin.gov.co/transito/images_jq/imagen40.jpg")
Camara.create(direccion: "Carrera 64AA - Calle 111 A", sector: "Autopista Norte - Deprimido Feria de Ganado", link: "http://www.medellin.gov.co/transito/images_jq/imagen41.jpg")
Camara.create(direccion: "Calle 37 - Carrera 50", sector: "Avenida 33 - Palace - AKT Motos", link: "http://www.medellin.gov.co/transito/images_jq/imagen42.jpg")
Camara.create(direccion: "Carrera 48 - Calle 7", sector: "Avenida Las Vegas - Calle 7 - Politecnico Jaime Isaza", link: "http://www.medellin.gov.co/transito/images_jq/imagen43.jpg")
Camara.create(direccion: "Carrera 25 - Calle 10", sector: "Transversal Superior - Cola del Zorro", link: "http://www.medellin.gov.co/transito/images_jq/imagen44.jpg")
Camara.create(direccion: "Carrera 37 - Calle 47 ", sector: "Carrera 37 - Calle 47 - Interseccion de Bomberos", link: "http://www.medellin.gov.co/transito/images_jq/imagen45.jpg")
Camara.create(direccion: "Carrera 57 - Calle 58A", sector: "Carrera 57 - Calle 58 - Glorieta de Fatelares", link: "http://www.medellin.gov.co/transito/images_jq/imagen46.jpg")
Camara.create(direccion: "Calle 10 - Carrera 49", sector: "Autopista Sur - Calle 10 - Puente de la 10", link: "http://www.medellin.gov.co/transito/images_jq/imagen47.jpg")
Camara.create(direccion: "Carrera 70 - Calle 14 Aeroparque", sector: "Carrera 70 - Aeroparque", link: "http://www.medellin.gov.co/transito/images_jq/imagen48.jpg")
Camara.create(direccion: "Calle 34 - Carrera 66B", sector: "Calle 34 - Exito de Unicentro - AV Villas", link: "http://www.medellin.gov.co/transito/images_jq/imagen49.jpg")

